// generated by Fast Light User Interface Designer (fluid) version 1.0104

#ifndef ESESCthermViewUI_h
#define ESESCthermViewUI_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Slider.H>
#include <FL/Fl_Box.H>
#include "ESESCthermView.h"
#include <FL/Fl_Value_Slider.H>

class ESESCthermViewUI {
public:
  ESESCthermViewUI();
private:
  Fl_Double_Window *mainWindow;
public:
  Fl_Group *VChange;
  Fl_Slider *ypan;
private:
  inline void cb_ypan_i(Fl_Slider*, void*);
  static void cb_ypan(Fl_Slider*, void*);
public:
  Fl_Group *HChange;
  Fl_Slider *xpan;
private:
  inline void cb_xpan_i(Fl_Slider*, void*);
  static void cb_xpan(Fl_Slider*, void*);
public:
  Fl_Group *MainView;
  Fl_Box *cframe;
  ESESCthermView *thermView;
  Fl_Value_Slider *zoom;
private:
  inline void cb_zoom_i(Fl_Value_Slider*, void*);
  static void cb_zoom(Fl_Value_Slider*, void*);
public:
  void show(int argc, char **argv);
};
#endif
