// generated by Fast Light User Interface Designer (fluid) version 1.0104

#include "SESCthermViewUI.h"

inline void SESCthermViewUI::cb_ypan_i(Fl_Slider* o, void*) {
  thermView->pany(((Fl_Slider *)o)->value());
thermView->redraw();
}
void SESCthermViewUI::cb_ypan(Fl_Slider* o, void* v) {
  ((SESCthermViewUI*)(o->parent()->parent()->parent()->user_data()))->cb_ypan_i(o,v);
}

inline void SESCthermViewUI::cb_xpan_i(Fl_Slider* o, void*) {
  thermView->panx(((Fl_Slider *)o)->value());
thermView->redraw();
}
void SESCthermViewUI::cb_xpan(Fl_Slider* o, void* v) {
  ((SESCthermViewUI*)(o->parent()->parent()->parent()->user_data()))->cb_xpan_i(o,v);
}

inline void SESCthermViewUI::cb_zoom_i(Fl_Value_Slider* o, void*) {
  thermView->size=((Fl_Value_Slider *)o)->value();
thermView->redraw();
}
void SESCthermViewUI::cb_zoom(Fl_Value_Slider* o, void* v) {
  ((SESCthermViewUI*)(o->parent()->parent()->user_data()))->cb_zoom_i(o,v);
}

SESCthermViewUI::SESCthermViewUI() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = mainWindow = new Fl_Double_Window(719, 656, "SESCthermView");
    w = o;
    o->box(FL_UP_BOX);
    o->labelsize(12);
    o->user_data((void*)(this));
    { Fl_Group* o = new Fl_Group(5, 3, 700, 637);
      { Fl_Group* o = VChange = new Fl_Group(5, 100, 37, 490);
        { Fl_Slider* o = ypan = new Fl_Slider(25, 100, 15, 490, "V Pan");
          o->type(4);
          o->selection_color(FL_DARK_BLUE);
          o->labeltype(FL_NO_LABEL);
          o->labelsize(12);
          o->minimum(-25);
          o->maximum(25);
          o->step(0.1);
          o->callback((Fl_Callback*)cb_ypan);
          o->align(FL_ALIGN_CENTER);
        }
        o->end();
      }
      { Fl_Group* o = HChange = new Fl_Group(120, 362, 530, 278);
        { Fl_Slider* o = xpan = new Fl_Slider(195, 623, 390, 17, "H Pan");
          o->type(5);
          o->selection_color(FL_DARK_BLUE);
          o->labeltype(FL_NO_LABEL);
          o->labelsize(12);
          o->minimum(25);
          o->maximum(-25);
          o->step(0.1);
          o->callback((Fl_Callback*)cb_xpan);
          o->align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
        }
        o->end();
      }
      { Fl_Group* o = MainView = new Fl_Group(46, 27, 659, 588);
        { Fl_Box* o = cframe = new Fl_Box(46, 27, 659, 583);
          o->box(FL_DOWN_FRAME);
          o->color((Fl_Color)4);
          o->selection_color((Fl_Color)69);
        }
        { SESCthermView* o = thermView = new SESCthermView(47, 29, 656, 579, "thermview");
          o->box(FL_NO_BOX);
          o->color(FL_BACKGROUND_COLOR);
          o->selection_color(FL_BACKGROUND_COLOR);
          o->labeltype(FL_NORMAL_LABEL);
          o->labelfont(0);
          o->labelsize(14);
          o->labelcolor(FL_BLACK);
          o->align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
          o->when(FL_WHEN_RELEASE);
        }
        o->end();
      }
      { Fl_Value_Slider* o = zoom = new Fl_Value_Slider(106, 3, 554, 19, "Zoom");
        o->type(5);
        o->selection_color(FL_DARK_BLUE);
        o->labelfont(1);
        o->labelsize(12);
        o->minimum(1);
        o->maximum(50);
        o->step(0.1);
        o->value(10);
        o->textfont(1);
        o->callback((Fl_Callback*)cb_zoom);
        o->align(FL_ALIGN_LEFT);
      }
      o->end();
    }
    o->end();
    o->resizable(o);
  }
}

void SESCthermViewUI::show(int argc, char **argv) {
  mainWindow->show(argc, argv);
}
